### ISSUE TITLE
[Feature] Replace static target humidity with rolling average

### ISSUE THREAD

**Issue by hugodejong** [avdeevsv91/ha_generic_hygrostat#1]
I use a switched fan to regulate the humidity in my bathroom. In dry weather, the humidity might go down to 40%, but in periods of rain, that might be 60%. It would be great if the hygrostat supported a dynamic target humidity based on the past x hours.

In my own implementation (in HA, not a custom component), I used a humidity sensor and an associated trend sensor to accomplish this:

```
sensor:
  - platform: statistics
    entity_id: sensor.bathroom_humidity
    name: Bathroom humidity statistics
    sampling_size: 100
    max_age:
      hours: 2
    precision: 1


binary_sensor:
  - platform: template
      bathroom_ventilator:
        friendly_name: Bathroom ventilator
        icon_template: "mdi:fan"
        value_template: "{{ states('sensor.bathroom_humidity')|float > (state_attr('sensor.bathroom_humidity_statistics', 'mean') + 10) }}" 
        delay_off:
          minutes: 3
```
